language: node_js
node_js:
  - "lts/*"

script:
  - yarn run lint
  - yarn run test

# deploy:
#   provider: heroku
#   api_key:
#     secure: "YOUR ENCRYPTED API KEY"
#   app:
#     master: zinovikbot