version: '3'

services:
  database:
    image: redis:latest
    restart: always
    ports:
      - 9379:6379

  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 8100:8100
    depends_on:
      - database
