name: Deploy to Google Cloud Functions
run-name: Deploy to Google Cloud Functions
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Save service account key file environment variable to file
        run: echo "${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY_FILE }}" | base64 -d >> key-file.json
      - name: Authenticate service account
        run: gcloud auth activate-service-account --key-file key-file.json
      - name: Remove key-file.json
        run: rm key-file.json
      - name: Save environment variables to yaml
        run: echo "${{ secrets.ENV }}" | base64 -d >> env.yaml
      - name: Build and Deploy
        run: npm run deploy
      - name: Remove env.yaml
        run: rm env.yaml
